### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by luoc0815** [openmicroanalysis/pyxray#11]
Building the database fails if `requests` package is not installed. Is it intended that it's not part of the requirements?

```
(env_auto) [vm-user@localhost pyxray]$ python setup.py build
running build
running build_py
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    entry_points=ENTRY_POINTS,
  File "/home/vm-user/Workspace/pymontecarlo_test/env_auto/lib64/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 22, in run
    builder.build()
  File "/home/vm-user/Workspace/pymontecarlo_test/pyxray/pyxray/sql/build.py", line 98, in build
    parsers = self._find_parsers()
  File "/home/vm-user/Workspace/pymontecarlo_test/pyxray/pyxray/sql/build.py", line 74, in _find_parsers
    return find_parsers()
  File "/home/vm-user/Workspace/pymontecarlo_test/pyxray/pyxray/parser/parser.py", line 40, in find_parsers
    parser = entry_point.load()
  File "/home/vm-user/Workspace/pymontecarlo_test/env_auto/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/vm-user/Workspace/pymontecarlo_test/env_auto/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vm-user/Workspace/pymontecarlo_test/pyxray/pyxray/parser/nist.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by ppinard** [comment]
It requires to install the "develop" dependencies.

```
pip install -e .[develop]
```

I updated the REAME.rst to mention this.
